### ISSUE TITLE
Error when running (Duplicate entry 'notion-entry_page_id' for key 'index_pages.category_name')

### ISSUE THREAD

**Issue by andyvauliln** [finaldie/auto-news#45]
i have problem to start it locally on mine macOS. The issue in container docker-airflow-init-user. And i can't see any notion tables crated. 
Logs From Container:
2023-12-13 12:53:13 Initializing Notion database tables...
2023-12-13 12:53:13 Notion initialization started ...
2023-12-13 12:53:13 MySQL client initialization finished, host: mysql-db, port: 3306, user: bot
2023-12-13 12:53:13 loaded indexes: {'notion': {'entry_page_id': {'index_id': '', 'created_at': datetime.datetime(2023, 12, 12, 19, 31, 54), 'updated_at': datetime.datetime(2023, 12, 12, 19, 31, 54)}}}
2023-12-13 12:53:13 loaded notion indexes: {'entry_page_id': {'index_id': '', 'created_at': datetime.datetime(2023, 12, 12, 19, 31, 54), 'updated_at': datetime.datetime(2023, 12, 12, 19, 31, 54)}}
2023-12-13 12:53:13 [ERROR] Errors in creating notion pages: 1062 (23000): Duplicate entry 'notion-entry_page_id' for key 'index_pages.category_name'
2023-12-13 12:53:06 /home/airflow/.local/lib/python3.11/site-packages/langchain/__init__.py:34: UserWarning: Importing LLMChain from langchain root module is no longer supported. Please use langchain.chains.LLMChain instead.
2023-12-13 12:53:06   warnings.warn(
2023-12-13 12:53:13 Traceback (most recent call last):
2023-12-13 12:53:13   File "/home/airflow/.local/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 633, in cmd_query
2023-12-13 12:53:13     self._cmysql.query(
2023-12-13 12:53:13 _mysql_connector.MySQLInterfaceError: Duplicate entry 'notion-entry_page_id' for key 'index_pages.category_name'
2023-12-13 12:53:13 
2023-12-13 12:53:13 The above exception was the direct cause of the following exception:
2023-12-13 12:53:13 
2023-12-13 12:53:13 Traceback (most recent call last):
2023-12-13 12:53:13   File "/home/airflow/airflow/run/auto-news/src/patches.py", line 63, in <module>
2023-12-13 12:53:13     apply_patches()
2023-12-13 12:53:13   File "/home/airflow/airflow/run/auto-news/src/patches.py", line 52, in apply_patches
2023-12-13 12:53:13     ok, msg = func()
2023-12-13 12:53:13               ^^^^^^
2023-12-13 12:53:13   File "/opt/airflow/run/auto-news/src/patch_0.py", line 14, in apply
2023-12-13 12:53:13     notion_init.init()
2023-12-13 12:53:13   File "/opt/airflow/run/auto-news/src/notion_init.py", line 8, in init
2023-12-13 12:53:13     op.init()
2023-12-13 12:53:13   File "/opt/airflow/run/auto-news/src/ops_notion.py", line 30, in init
2023-12-13 12:53:13     db_cli.index_pages_table_insert(
2023-12-13 12:53:13   File "/opt/airflow/run/auto-news/src/mysql_cli.py", line 110, in index_pages_table_insert
2023-12-13 12:53:13     c.execute(sql, val)
2023-12-13 12:53:13   File "/home/airflow/.local/lib/python3.11/site-packages/mysql/connector/cursor_cext.py", line 330, in execute
2023-12-13 12:53:13     result = self._cnx.cmd_query(
2023-12-13 12:53:13              ^^^^^^^^^^^^^^^^^^^^
2023-12-13 12:53:13   File "/home/airflow/.local/lib/python3.11/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 86, in wrapper
2023-12-13 12:53:13     result = method(cnx, *args, **kwargs)
2023-12-13 12:53:13              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-13 12:53:13   File "/home/airflow/.local/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 641, in cmd_query
2023-12-13 12:53:13     raise get_mysql_exception(
2023-12-13 12:53:13 mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'notion-entry_page_id' for key 'index_pages.category_name'
2023-12-13 12:53:14 Apply patches finished
2023-12-13 12:53:14 ----
2023-12-13 12:53:19 Enable DAGs...
2023-12-13 12:53:24 Dag: news_pulling, paused: False
2023-12-13 12:53:27 Dag: sync_dist, paused: False
2023-12-13 12:53:31 Dag: collection_weekly, paused: False
2023-12-13 12:53:34 Dag: upgrade, paused: False
2023-12-13 12:53:37 Dag: journal_daily, paused: False
2023-12-13 12:53:41 Dag: action, paused: False
2023-12-13 12:53:41 Enable DAGs finished

**Comment by finaldie** [comment]
Hi @andyvauliln , 

Thanks for reporting the issue. I reproduced your case locally, from the logs and your description, I believe this is the first time you were trying to create/start the `auto-news` service. And it happens when we `miss` enabling the [Notion Connection](https://www.notion.so/my-integrations) for the `main entry page`, and this is the required setup step before starting the auto-news services.

Currently, we left some of the dirty data since the initialization step failed, instead of fixing the database, I'd suggest to re-deploy it completely.

## Steps for the fix
1. Enabling the [Notion Connection](https://www.notion.so/my-integrations) for the `main entry page` we just created, below is my testing entry page example (see the `connections` section, if empty, click the plus sign, and add yours there)
![image](https://github.com/finaldie/auto-news/assets/1088543/5d105f5e-79c7-475e-ba2a-5f8c4e5fb809)

2. Stop the auto-news services: `make stop`

3. Go to the terminal, and enter the code base root location, then delete the `workspace` folder: `rm -rf workspace`

4. Redeploy and start the auto-news services again: `make deploy && make init && make start`

----

Now, it should start correctly (all the initial notion pages will be created automatically). Let me know if that works for u.

**Comment by andyvauliln** [comment]
oh ... thanks, i tried a lot but yes after rm -rf workspace it started work again
