### ISSUE TITLE
Error on first startup ( body failed validation: body.children should be an array or `undefined`, instead was `null`.)

### ISSUE THREAD

**Issue by xlzuvekas** [finaldie/auto-news#51]
I am continually running into issues upon initial startup. 

startup process from clean install:
sudo rm -rf auto-news 
git clone https://github.com/finaldie/auto-news/
cd auto-news
code . (update env variables)
make deps && make build && make deploy && make init
make start

The issue is in the container docker-airflow-init-user. No pages are created within notion. The notion page  is blank aside from a title 'reader'.

2024-01-19 12:38:11 httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/pages'
2024-01-19 12:38:11 For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
2024-01-19 12:38:11 
2024-01-19 12:38:11 During handling of the above exception, another exception occurred:
2024-01-19 12:38:11 
2024-01-19 12:38:11 Traceback (most recent call last):
2024-01-19 12:38:11   File "/home/airflow/airflow/run/auto-news/src/patches.py", line 63, in <module>
2024-01-19 12:38:11     apply_patches()
2024-01-19 12:38:11   File "/home/airflow/airflow/run/auto-news/src/patches.py", line 52, in apply_patches
2024-01-19 12:38:11     ok, msg = func()
2024-01-19 12:38:11               ^^^^^^
2024-01-19 12:38:11   File "/opt/airflow/run/auto-news/src/patch_0.py", line 14, in apply
2024-01-19 12:38:11     notion_init.init()
2024-01-19 12:38:11   File "/opt/airflow/run/auto-news/src/notion_init.py", line 8, in init
2024-01-19 12:38:11     op.init()
2024-01-19 12:38:11   File "/opt/airflow/run/auto-news/src/ops_notion.py", line 34, in init
2024-01-19 12:38:11     inbox_page = agent.createPageOfPage(entry_page_id, "Inbox")
2024-01-19 12:38:11                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-19 12:38:11   File "/opt/airflow/run/auto-news/src/notion.py", line 1921, in createPageOfPage
2024-01-19 12:38:11     return self.createPage(parent, props, None)
2024-01-19 12:38:11            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-19 12:38:11   File "/opt/airflow/run/auto-news/src/notion.py", line 1924, in createPage
2024-01-19 12:38:11     new_page = self.api.pages.create(
2024-01-19 12:38:11                ^^^^^^^^^^^^^^^^^^^^^^
2024-01-19 12:38:11   File "/home/airflow/.local/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 208, in create
2024-01-19 12:38:11     return self.parent.request(
2024-01-19 12:38:11            ^^^^^^^^^^^^^^^^^^^^
2024-01-19 12:38:11   File "/home/airflow/.local/lib/python3.11/site-packages/notion_client/client.py", line 194, in request
2024-01-19 12:38:11     return self._parse_response(response)
2024-01-19 12:38:11            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-19 12:38:11   File "/home/airflow/.local/lib/python3.11/site-packages/notion_client/client.py", line 126, in _parse_response
2024-01-19 12:38:11     raise APIResponseError(response, body["message"], code)
2024-01-19 12:38:11 notion_client.errors.APIResponseError: body failed validation: body.children should be an array or `undefined`, instead was `null`.

**Comment by finaldie** [comment]
hi @xlzuvekas 

Thanks for reporting the issue, after investigation, it's due to the compatibility issue for the latest notion-client 2.2.1, I've prepared the patch (https://github.com/finaldie/auto-news/pull/52), will merge it soon.

Please update to the latest codebase, and:
- Remove the `workspace` folder
- Then run: `make deps && make deploy && make init && make start`, to kick-off the services again.

**Comment by xlzuvekas** [comment]
Incredible! Thank you so much! 

I really appreciate your help!
