### ISSUE TITLE
openai.RateLimitError: Error code: 429 (API keys never used)

### ISSUE THREAD

**Issue by flowcool** [finaldie/auto-news#88]
Hello,

I'm very much interested into this project but... cannot make it work.

I deployed it using portainer, adjusted everything and tried to configured with OpenAi then Gemini.
I still don't see any news coming.

Having a look to airflow logs, I'm seeing this :
`[2024-08-27, 06:22:28 UTC] {subprocess.py:93} INFO - openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}`

Which doesn't make sense as you can see below:
![2024-08-27_08h38_01](https://github.com/user-attachments/assets/4faad2a8-09cb-4e15-bdcc-61d214f0c878)

Is there an hardcoded key some where ?
Especially in that case, where I specifically mentioned Gemini, so i don't understand how OpenAi is coming, and even though, it seems it doesn't reach my API Key.

Any clue ?

**Comment by flowcool** [comment]
Just thinking about something:
I didn't put anything on variable below (as I don't know what to put):
```
AUTOGEN_GPT3_API_KEY=
AUTOGEN_GPT4_API_KEY=

```

But only filled next one:
`OPENAI_API_KEY=`

Is that correct or should i put same key everywhere ?

**Comment by finaldie** [comment]
Hi @flowcool 

There is no hardcoded key, it only rely on the `.env` config.

`AUTOGEN_GPT3_API_KEY` and `AUTOGEN_GPT4_API_KEY` are only for the experiment features; we can ignore them in your case.

Your above error log shows that your key is exceeding the quota. If this is a new key, it shouldn't be, but it may be that your account hasn't assigned enough budget for it. You may want to double-check.

The other way to check is to modify the `LLM_PROVIDER=google` and add a Google Gemini key, as it is free and has a good amount of quota for testing. [ref](https://ai.google.dev/pricing)

**Comment by flowcool** [comment]
Hello,

thanks for the reply. As mentioned, I put (and let) google) during the whole night....and I still see next error, referring to OpenAi (and my openai API Key, still showing: Never used).

```
[2024-08-28, 06:21:22 UTC] {subprocess.py:93} INFO - [get_relevant] Fallback collection name: news_embedding__2024_08_27
[2024-08-28, 06:21:25 UTC] {subprocess.py:93} INFO - [ERROR] RateLimitError during embedding (1/3): Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
[2024-08-28, 06:21:31 UTC] {subprocess.py:93} INFO - [ERROR] RateLimitError during embedding (2/3): Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO - [ERROR] RateLimitError during embedding (3/3): Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO - [ERROR]: Score page failed, skip: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -   File "/opt/***/run/auto-news/src/ops_reddit.py", line 323, in score
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -     relevant_metas = op_milvus.get_relevant(
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -                      ^^^^^^^^^^^^^^^^^^^^^^^
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -   File "/opt/***/run/auto-news/src/ops_milvus.py", line 152, in get_relevant
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -     embedding = emb_agent.get_or_create(
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -                 ^^^^^^^^^^^^^^^^^^^^^^^^
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -   File "/opt/***/run/auto-news/src/embedding_agent.py", line 52, in get_or_create
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -     return self.model.get_or_create(text, source, page_id, db_client, key_ttl)
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -   File "/opt/***/run/auto-news/src/embedding_openai.py", line 46, in get_or_create
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -     return self.instance.get_or_create(
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -   File "/opt/***/run/auto-news/src/embedding_openai_1x.py", line 105, in get_or_create
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -     embedding = self.create(text[:EMBEDDING_MAX_LENGTH])
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -   File "/opt/***/run/auto-news/src/embedding_openai_1x.py", line 50, in create
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -     emb = self.client.embeddings.create(
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/openai/resources/embeddings.py", line 114, in create
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -     return self._post(
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -            ^^^^^^^^^^^
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/openai/_base_client.py", line 1250, in post
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/openai/_base_client.py", line 931, in request
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -     return self._request(
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/openai/_base_client.py", line 1015, in _request
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -     return self._retry_request(
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/openai/_base_client.py", line 1063, in _retry_request
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -     return self._request(
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/openai/_base_client.py", line 1015, in _request
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -     return self._retry_request(
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/openai/_base_client.py", line 1063, in _retry_request
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -     return self._request(
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/openai/_base_client.py", line 1030, in _request
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO -     raise self._make_status_error_from_response(err.response) from None
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO - openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO - [EmbeddingAgent] provider: openai, model_name: text-embedding-ada-002
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO - Initialized EmbeddingOpenAI 1x: 1.35.8
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO - Initialized EmbeddingOpenAI Interface: openai version 1.35.8
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO - [get_relevant] collection_name: news_embedding__2024_08_28
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO - [MilvusClient] server.alias: default, host: milvus-standalone, port: 19530
[2024-08-28, 06:21:37 UTC] {subprocess.py:93} INFO - [get_relevant] Fallback collection name: news_embedding__2024_08_27
[2024-08-28, 06:21:41 UTC] {subprocess.py:93} INFO - [ERROR] RateLimitError during embedding (1/3): Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
[2024-08-28, 06:21:47 UTC] {subprocess.py:93} INFO - [ERROR] RateLimitError during embedding (2/3): Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
[2024-08-28, 06:21:53 UTC] {subprocess.py:93} INFO - [ERROR] RateLimitError during embedding (3/3): Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
[2024-08-28, 06:21:53 UTC] {subprocess.py:93} INFO - [ERROR]: Score page failed, skip: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
[2024-08-28, 06:21:53 UTC] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-08-28, 06:21:53 UTC] {subprocess.py:93} INFO -   File "/opt/***/run/auto-news/src/ops_reddit.py", line 323, in score
[2024-08-28, 06:21:53 UTC] {subprocess.py:93} INFO -     relevant_metas = op_milvus.get_relevant(
```

I'm completely lost about what's going on. I even deleted everything and rebuild the overall, but doesn't change anything

**Comment by flowcool** [comment]
Ok, so after (re)deleting everything again and recreating, it finally took gemini.... Does it mean once setup, we cannot change model ? (without deleting everything)

**Comment by finaldie** [comment]
Oh, I see. Thanks for providing the detailed log. It's from the embedding generation path. I believe your open API key setup may have something wrong, which prevents your app from querying it.

Do you mind creating another open API key and ensure it has enough budget to be used? Then we can try again.

Steps:
1. Re-create the API key
2. Replace the `OPENAI_API_KEY` environment variable with the new key in your `build/.env`.
3. Restart service

**Comment by flowcool** [comment]
Jeeeeeeeeeeez ! Finally, for everyone:
I tried:
user api key
service api key
You api key <- this one looks to work !!

Many thanks, I spent my day trying to read your scripts and understanding where it was crashing !! Now I'll waiting to have these processing and play with it tomorrow !!

**Comment by finaldie** [comment]
Cheers! :+1: Glad to see that works for you, I appreciated your help in letting more people know it. Enjoy the peace of the day, and feel free to drop any issues/thoughts, we could make it better together.

**Comment by flowcool** [comment]
I'll wait a few hour (tomorrow ) and close it, juste to make sure we're all good ;)

**Comment by flowcool** [comment]
Actually no :( Same error coming back.
and same behavior on OpenAI: API KEY: Never used

I had a look in the code (again, spent my day) and noticed on src/embedding_openai_1x.py there's no mention of API key (in comparison to 0x). Could it be linked ?

very sorry for all this :(

**Comment by finaldie** [comment]
Sorry to hear that. I found an OpenAI thread that discussed this issue https://community.openai.com/t/i-keep-getting-an-error-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details-even-though-my-account-has-sufficient-credits/537053

It may be due to no available credit, the shared account already using all the query quota (not likely), or some other issue inside Openai.

Someone mentioned that creating a new API key may solve the problem. If it hasn't been done yet, suggest to try it as well. (By the way, prefer to create the project API key instead of the legacy user key.) We may be lucky on the next try :)

**Comment by flowcool** [comment]
I finally put 10 bucks on OpenAi and here we go.... I thought free account would work but no.
